version: '3'

services:

  symfony-db:
    container_name: symfony-db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - dev

  symfony-php:
    container_name: symfony-php
    build:
      context: ./docker/php
    ports:
      - '9000'
    volumes:
      - ./src:/var/www/symfony_docker
    depends_on:
      - symfony-db
    networks:
      - dev

  symfony-nginx:
    container_name: symfony-nginx
    image: nginx:stable-alpine
    ports:
      - '80'
    volumes:
      - ./src:/var/www/symfony_docker
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - symfony-php
      - symfony-db
    networks:
      - dev

networks:
  dev:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/26
